sf data create file --file 'FeatureSetupData/Presentation/Files/01/01_Patients with arterial hypertension.pdf'
sf data create file --file 'FeatureSetupData/Presentation/Files/01/01_Patients with arterial hypertension.zip'
sf data create file --file 'FeatureSetupData/Presentation/Files/01/01_thumbnail.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/02/02_Risks and prevalence.pdf'
sf data create file --file 'FeatureSetupData/Presentation/Files/02/02_Risks and prevalence.zip'
sf data create file --file 'FeatureSetupData/Presentation/Files/02/02_thumbnail.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/03/03_Graph.pdf'
sf data create file --file 'FeatureSetupData/Presentation/Files/03/03_Graph.zip'
sf data create file --file 'FeatureSetupData/Presentation/Files/03/03_thumbnail.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/04/04_thumbnail.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/04/04_Video.pdf'
sf data create file --file 'FeatureSetupData/Presentation/Files/04/04_Video.zip'
sf data create file --file 'FeatureSetupData/Presentation/Files/pdf/pdf_thumbnail_01.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/pdf/pdf_thumbnail_02.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/pdf/pdf_thumbnail_03.jpg'
sf data create file --file 'FeatureSetupData/Presentation/Files/pdf/Life Sciences Cloud Customer Engagement Developer Guide (Pilot).pdf'

sf apex run --file Scripts/apex/presentation_page_file_load.apex