{
    "records": [
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "AccountDynamicListConfigurationRecordRef1"
            },
            "LifeScienceMetadataCategoryId": "@AccountDynamicListConfigurationRef1",
            "IsActive": true,
            "IsOrgLevel": true,
            "Name": "AccountDynamicListConfiguration_OrgLevel",
            "ParentMetadataRecordId": null,
            "RecordApiName": "AccountDynamicListConfiguration_AccountDynamicListConfiguration_OrgLevel",
            "Type": null
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "AccountFilterConfigRecordRef1"
            },
            "LifeScienceMetadataCategoryId": "@AccountFilterConfigRef1",
            "IsActive": true,
            "IsOrgLevel": true,
            "Name": "AccountFilterConfig_OrgLevel",
            "ParentMetadataRecordId": null,
            "RecordApiName": "AccountFilterConfig_AccountFilterConfig_OrgLevel",
            "Type": null
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "AccountListActionsRecordRef1"
            },
            "Name": "AccountListActions_OrgLevel",
            "LifeScienceMetadataCategoryId": "@AccountListActionsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "AccountListActions_AccountListActions_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "ProviderVisitSettingsRecordRef1"
            },
            "Name": "ProviderVisitSettings_OrgLevel",
            "LifeScienceMetadataCategoryId": "@ProviderVisitSettingsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "ProviderVisitSettings_ProviderVisitSettings_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "AccountSearchPreferencesRecordRef1"
            },
            "Name": "AccountSearchPreferences_OrgLevel",
            "LifeScienceMetadataCategoryId": "@AccountSearchPreferencesRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "AccountSearchPreferences_AccountSearchPreferences_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "PresentationSettingsRecordRef1"
            },
            "Name": "PresentationSettings_OrgLevel",
            "LifeScienceMetadataCategoryId": "@PresentationSettingsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "PresentationSettings_PresentationSettings_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "EmailSettingsRecordRef1"
            },
            "Name": "EmailSettings_OrgLevel",
            "LifeScienceMetadataCategoryId": "@EmailSettingsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "EmailSettings_EmailSettings_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "InventoryManagementProfileSettingsRecordRef1"
            },
            "Name": "InventoryManagementProfileSettings_OrgLevel",
            "LifeScienceMetadataCategoryId": "@InventoryManagementProfileSettingsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "InventoryManagementProfileSettings_InventoryManagementProfileSettings_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "ExternalSearchSettingsRecordRef1"
            },
            "Name": "ExternalSearchSettings_OrgLevel",
            "LifeScienceMetadataCategoryId": "@ExternalSearchSettingsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "ExternalSearchSettings_ExternalSearchSettings_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        },
        {
            "attributes": {
                "type": "LifeSciMetadataRecord",
                "referenceId": "SampleLimitSettingsRecordRef1"
            },
            "Name": "SampleLimitSettings_OrgLevel",
            "LifeScienceMetadataCategoryId": "@SampleLimitSettingsRef1",
            "ParentMetadataRecordId": null,
            "RecordApiName": "SampleLimitSettings_SampleLimitSettings_OrgLevel",
            "Type": null,
            "IsActive": true,
            "IsOrgLevel": true
        }
    ]
}